import os
import ast
import csv

def generate_test_reports_from_code():
    """
    This script analyzes the test files and generates reports
    without actually running the tests.
    """
    print("Analyzing test files and generating reports...")

    test_dir = os.path.join(os.path.dirname(__file__), 'tests')
    report_path = os.path.join(os.path.dirname(__file__), 'test_reports', 'unit_test_plan_report.csv')

    test_files = [f for f in os.listdir(test_dir) if f.startswith('test_') and f.endswith('.py')]

    with open(report_path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Test File', 'Test Case', 'Status'])

        for test_file in test_files:
            try:
                with open(os.path.join(test_dir, test_file), 'r') as f_in:
                    tree = ast.parse(f_in.read())
                    for node in ast.walk(tree):
                        if isinstance(node, ast.FunctionDef) and node.name.startswith('test_'):
                            writer.writerow([test_file, node.name, 'NotRun'])
            except Exception as e:
                print(f"Error parsing {test_file}: {e}")


    print(f"Unit test report generated at: {report_path}")
    print("\nNote: This report is generated by analyzing the test code, not by running the tests.")

if __name__ == '__main__':
    generate_test_reports_from_code()
